//EL PRINCIPIO DE RESPONSABILIDAD UNICA, VAMOS A PROCEDER A FRAGMENTAR ESTE FILE, LO CUAL SIGNIFICA CREAR UN ARCHIVO CON PROPOSITO UNICO, ES DECIR UN ARCHIVO PO CADA UNA DE LAS CLASES.

export enum PhotoOrientation {
    Landscape,
    Portrait,
    Square,
    Panorama,
}